apiVersion: v1
kind: Service
metadata:
  name: kratos
  labels:
    app: kratos
spec:
  ports:
  - port: 4433
    name: public
    targetPort: 4433
  - port: 4434
    name: admin
    targetPort: 4434
  selector:
    app: kratos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
  labels:
    app: kratos
spec:
  selector:
    matchLabels:
      app: kratos
  template:
    metadata:
      labels:
        app: kratos
    spec:
      initContainers:
      - name: kratos-migrate
        image: ghcr.io/canonical/kratos:25.4.0
        command: ["kratos", "-c", "/etc/config/kratos/kratos.yml", "migrate", "sql", "-e", "--yes"]
        env:
        - name: DSN
          value: postgres://kratos:kratos@postgres:5432/kratos?sslmode=disable
        volumeMounts:
        - name: kratos-config
          mountPath: /etc/config/kratos
      containers:
      - name: kratos
        image: ghcr.io/canonical/kratos:25.4.0
        command: ["kratos", "serve", "-c", "/etc/config/kratos/kratos.yml", "--dev", "--watch-courier"]
        env:
        - name: DSN
          value: postgres://kratos:kratos@postgres:5432/kratos?sslmode=disable
        - name: LOG_LEVEL
          value: trace
        - name: SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kratos
              key: client-id
        - name: SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kratos
              key: client-secret
        ports:
        - containerPort: 4433
          name: public
        - containerPort: 4434
          name: admin
        volumeMounts:
        - name: kratos-config
          mountPath: /etc/config/kratos
      volumes:
      - name: kratos-config
        configMap:
          name: kratos-config
