apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hydra.yaml
  - kratos.yaml

configMapGenerator:
  - name: hydra-config
    files:
      - ../hydra/hydra.yml
  - name: kratos-config
    files:
      - ../kratos/kratos.yml
      - ../kratos/identity.json
      - ../kratos/identity.schema.json
      - ../kratos/schema.jsonnet

secretGenerator:
  - name: kratos
    envs:
      - ../secrets/kratos.env
  - name: hydra-credentials
    literals:
      - client-secret=secret

generatorOptions:
  disableNameSuffixHash: true
