// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/repository (interfaces: ServiceProviderRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_service_provider_repository.go -package=mocks . ServiceProviderRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/canonical/identity-saml-provider/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceProviderRepository is a mock of ServiceProviderRepository interface.
type MockServiceProviderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceProviderRepositoryMockRecorder
	isgomock struct{}
}

// MockServiceProviderRepositoryMockRecorder is the mock recorder for MockServiceProviderRepository.
type MockServiceProviderRepositoryMockRecorder struct {
	mock *MockServiceProviderRepository
}

// NewMockServiceProviderRepository creates a new mock instance.
func NewMockServiceProviderRepository(ctrl *gomock.Controller) *MockServiceProviderRepository {
	mock := &MockServiceProviderRepository{ctrl: ctrl}
	mock.recorder = &MockServiceProviderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceProviderRepository) EXPECT() *MockServiceProviderRepositoryMockRecorder {
	return m.recorder
}

// GetAttributeMapping mocks base method.
func (m *MockServiceProviderRepository) GetAttributeMapping(ctx context.Context, entityID string) (*domain.AttributeMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributeMapping", ctx, entityID)
	ret0, _ := ret[0].(*domain.AttributeMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributeMapping indicates an expected call of GetAttributeMapping.
func (mr *MockServiceProviderRepositoryMockRecorder) GetAttributeMapping(ctx, entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributeMapping", reflect.TypeOf((*MockServiceProviderRepository)(nil).GetAttributeMapping), ctx, entityID)
}

// GetByEntityID mocks base method.
func (m *MockServiceProviderRepository) GetByEntityID(ctx context.Context, entityID string) (*domain.ServiceProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEntityID", ctx, entityID)
	ret0, _ := ret[0].(*domain.ServiceProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEntityID indicates an expected call of GetByEntityID.
func (mr *MockServiceProviderRepositoryMockRecorder) GetByEntityID(ctx, entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEntityID", reflect.TypeOf((*MockServiceProviderRepository)(nil).GetByEntityID), ctx, entityID)
}

// Save mocks base method.
func (m *MockServiceProviderRepository) Save(ctx context.Context, sp *domain.ServiceProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, sp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockServiceProviderRepositoryMockRecorder) Save(ctx, sp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockServiceProviderRepository)(nil).Save), ctx, sp)
}
