// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/service (interfaces: PendingRequestService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_pending_request_service.go -package=mocks . PendingRequestService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/canonical/identity-saml-provider/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPendingRequestService is a mock of PendingRequestService interface.
type MockPendingRequestService struct {
	ctrl     *gomock.Controller
	recorder *MockPendingRequestServiceMockRecorder
	isgomock struct{}
}

// MockPendingRequestServiceMockRecorder is the mock recorder for MockPendingRequestService.
type MockPendingRequestServiceMockRecorder struct {
	mock *MockPendingRequestService
}

// NewMockPendingRequestService creates a new mock instance.
func NewMockPendingRequestService(ctrl *gomock.Controller) *MockPendingRequestService {
	mock := &MockPendingRequestService{ctrl: ctrl}
	mock.recorder = &MockPendingRequestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingRequestService) EXPECT() *MockPendingRequestServiceMockRecorder {
	return m.recorder
}

// Retrieve mocks base method.
func (m *MockPendingRequestService) Retrieve(ctx context.Context, requestID string) (*domain.PendingAuthnRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", ctx, requestID)
	ret0, _ := ret[0].(*domain.PendingAuthnRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockPendingRequestServiceMockRecorder) Retrieve(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockPendingRequestService)(nil).Retrieve), ctx, requestID)
}

// Store mocks base method.
func (m *MockPendingRequestService) Store(ctx context.Context, req *domain.PendingAuthnRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockPendingRequestServiceMockRecorder) Store(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockPendingRequestService)(nil).Store), ctx, req)
}
