// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/monitoring (interfaces: MonitorInterface)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_monitor.go -package=mocks . MonitorInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMonitorInterface is a mock of MonitorInterface interface.
type MockMonitorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorInterfaceMockRecorder
	isgomock struct{}
}

// MockMonitorInterfaceMockRecorder is the mock recorder for MockMonitorInterface.
type MockMonitorInterfaceMockRecorder struct {
	mock *MockMonitorInterface
}

// NewMockMonitorInterface creates a new mock instance.
func NewMockMonitorInterface(ctrl *gomock.Controller) *MockMonitorInterface {
	mock := &MockMonitorInterface{ctrl: ctrl}
	mock.recorder = &MockMonitorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorInterface) EXPECT() *MockMonitorInterfaceMockRecorder {
	return m.recorder
}

// IncrementBridgeOperation mocks base method.
func (m *MockMonitorInterface) IncrementBridgeOperation(operation, result string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementBridgeOperation", operation, result)
}

// IncrementBridgeOperation indicates an expected call of IncrementBridgeOperation.
func (mr *MockMonitorInterfaceMockRecorder) IncrementBridgeOperation(operation, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementBridgeOperation", reflect.TypeOf((*MockMonitorInterface)(nil).IncrementBridgeOperation), operation, result)
}

// IncrementHTTPRequestsTotal mocks base method.
func (m *MockMonitorInterface) IncrementHTTPRequestsTotal(method, route, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementHTTPRequestsTotal", method, route, status)
}

// IncrementHTTPRequestsTotal indicates an expected call of IncrementHTTPRequestsTotal.
func (mr *MockMonitorInterfaceMockRecorder) IncrementHTTPRequestsTotal(method, route, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementHTTPRequestsTotal", reflect.TypeOf((*MockMonitorInterface)(nil).IncrementHTTPRequestsTotal), method, route, status)
}

// ObserveHTTPRequestDuration mocks base method.
func (m *MockMonitorInterface) ObserveHTTPRequestDuration(method, route, status string, durationSeconds float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveHTTPRequestDuration", method, route, status, durationSeconds)
}

// ObserveHTTPRequestDuration indicates an expected call of ObserveHTTPRequestDuration.
func (mr *MockMonitorInterfaceMockRecorder) ObserveHTTPRequestDuration(method, route, status, durationSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveHTTPRequestDuration", reflect.TypeOf((*MockMonitorInterface)(nil).ObserveHTTPRequestDuration), method, route, status, durationSeconds)
}
