// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/service (interfaces: ServiceProviderService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_service_provider_service.go -package=mocks . ServiceProviderService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/canonical/identity-saml-provider/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceProviderService is a mock of ServiceProviderService interface.
type MockServiceProviderService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceProviderServiceMockRecorder
	isgomock struct{}
}

// MockServiceProviderServiceMockRecorder is the mock recorder for MockServiceProviderService.
type MockServiceProviderServiceMockRecorder struct {
	mock *MockServiceProviderService
}

// NewMockServiceProviderService creates a new mock instance.
func NewMockServiceProviderService(ctrl *gomock.Controller) *MockServiceProviderService {
	mock := &MockServiceProviderService{ctrl: ctrl}
	mock.recorder = &MockServiceProviderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceProviderService) EXPECT() *MockServiceProviderServiceMockRecorder {
	return m.recorder
}

// ClearAttributeMapping mocks base method.
func (m *MockServiceProviderService) ClearAttributeMapping(ctx context.Context, entityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAttributeMapping", ctx, entityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearAttributeMapping indicates an expected call of ClearAttributeMapping.
func (mr *MockServiceProviderServiceMockRecorder) ClearAttributeMapping(ctx, entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAttributeMapping", reflect.TypeOf((*MockServiceProviderService)(nil).ClearAttributeMapping), ctx, entityID)
}

// GetByEntityID mocks base method.
func (m *MockServiceProviderService) GetByEntityID(ctx context.Context, entityID string) (*domain.ServiceProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEntityID", ctx, entityID)
	ret0, _ := ret[0].(*domain.ServiceProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEntityID indicates an expected call of GetByEntityID.
func (mr *MockServiceProviderServiceMockRecorder) GetByEntityID(ctx, entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEntityID", reflect.TypeOf((*MockServiceProviderService)(nil).GetByEntityID), ctx, entityID)
}

// Register mocks base method.
func (m *MockServiceProviderService) Register(ctx context.Context, sp *domain.ServiceProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, sp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockServiceProviderServiceMockRecorder) Register(ctx, sp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockServiceProviderService)(nil).Register), ctx, sp)
}

// UpdateAttributeMapping mocks base method.
func (m *MockServiceProviderService) UpdateAttributeMapping(ctx context.Context, entityID string, mapping *domain.AttributeMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttributeMapping", ctx, entityID, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAttributeMapping indicates an expected call of UpdateAttributeMapping.
func (mr *MockServiceProviderServiceMockRecorder) UpdateAttributeMapping(ctx, entityID, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttributeMapping", reflect.TypeOf((*MockServiceProviderService)(nil).UpdateAttributeMapping), ctx, entityID, mapping)
}
