// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/service (interfaces: OIDCService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_oidc_service.go -package=mocks . OIDCService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/canonical/identity-saml-provider/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCService is a mock of OIDCService interface.
type MockOIDCService struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCServiceMockRecorder
	isgomock struct{}
}

// MockOIDCServiceMockRecorder is the mock recorder for MockOIDCService.
type MockOIDCServiceMockRecorder struct {
	mock *MockOIDCService
}

// NewMockOIDCService creates a new mock instance.
func NewMockOIDCService(ctrl *gomock.Controller) *MockOIDCService {
	mock := &MockOIDCService{ctrl: ctrl}
	mock.recorder = &MockOIDCServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCService) EXPECT() *MockOIDCServiceMockRecorder {
	return m.recorder
}

// AuthCodeURL mocks base method.
func (m *MockOIDCService) AuthCodeURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthCodeURL indicates an expected call of AuthCodeURL.
func (mr *MockOIDCServiceMockRecorder) AuthCodeURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockOIDCService)(nil).AuthCodeURL), state)
}

// ExchangeCode mocks base method.
func (m *MockOIDCService) ExchangeCode(ctx context.Context, code string) (*service.OIDCClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code)
	ret0, _ := ret[0].(*service.OIDCClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockOIDCServiceMockRecorder) ExchangeCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockOIDCService)(nil).ExchangeCode), ctx, code)
}
