// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/service (interfaces: MappingService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_mapping_service.go -package=mocks . MappingService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/canonical/identity-saml-provider/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMappingService is a mock of MappingService interface.
type MockMappingService struct {
	ctrl     *gomock.Controller
	recorder *MockMappingServiceMockRecorder
	isgomock struct{}
}

// MockMappingServiceMockRecorder is the mock recorder for MockMappingService.
type MockMappingServiceMockRecorder struct {
	mock *MockMappingService
}

// NewMockMappingService creates a new mock instance.
func NewMockMappingService(ctrl *gomock.Controller) *MockMappingService {
	mock := &MockMappingService{ctrl: ctrl}
	mock.recorder = &MockMappingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappingService) EXPECT() *MockMappingServiceMockRecorder {
	return m.recorder
}

// ApplyMapping mocks base method.
func (m *MockMappingService) ApplyMapping(ctx context.Context, session *domain.Session, entityID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyMapping", ctx, session, entityID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyMapping indicates an expected call of ApplyMapping.
func (mr *MockMappingServiceMockRecorder) ApplyMapping(ctx, session, entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyMapping", reflect.TypeOf((*MockMappingService)(nil).ApplyMapping), ctx, session, entityID)
}
