// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/repository (interfaces: PendingRequestRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_pending_request_repository.go -package=mocks . PendingRequestRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/canonical/identity-saml-provider/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPendingRequestRepository is a mock of PendingRequestRepository interface.
type MockPendingRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPendingRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockPendingRequestRepositoryMockRecorder is the mock recorder for MockPendingRequestRepository.
type MockPendingRequestRepositoryMockRecorder struct {
	mock *MockPendingRequestRepository
}

// NewMockPendingRequestRepository creates a new mock instance.
func NewMockPendingRequestRepository(ctrl *gomock.Controller) *MockPendingRequestRepository {
	mock := &MockPendingRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPendingRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingRequestRepository) EXPECT() *MockPendingRequestRepositoryMockRecorder {
	return m.recorder
}

// DeleteExpired mocks base method.
func (m *MockPendingRequestRepository) DeleteExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockPendingRequestRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockPendingRequestRepository)(nil).DeleteExpired), ctx)
}

// GetAndDelete mocks base method.
func (m *MockPendingRequestRepository) GetAndDelete(ctx context.Context, requestID string) (*domain.PendingAuthnRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndDelete", ctx, requestID)
	ret0, _ := ret[0].(*domain.PendingAuthnRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAndDelete indicates an expected call of GetAndDelete.
func (mr *MockPendingRequestRepositoryMockRecorder) GetAndDelete(ctx, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndDelete", reflect.TypeOf((*MockPendingRequestRepository)(nil).GetAndDelete), ctx, requestID)
}

// Save mocks base method.
func (m *MockPendingRequestRepository) Save(ctx context.Context, req *domain.PendingAuthnRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPendingRequestRepositoryMockRecorder) Save(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPendingRequestRepository)(nil).Save), ctx, req)
}
