// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/service (interfaces: SessionService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_session_service.go -package=mocks . SessionService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/canonical/identity-saml-provider/internal/domain"
	service "github.com/canonical/identity-saml-provider/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// CleanupExpired mocks base method.
func (m *MockSessionService) CleanupExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpired indicates an expected call of CleanupExpired.
func (mr *MockSessionServiceMockRecorder) CleanupExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpired", reflect.TypeOf((*MockSessionService)(nil).CleanupExpired), ctx)
}

// CreateFromOIDC mocks base method.
func (m *MockSessionService) CreateFromOIDC(ctx context.Context, claims *service.OIDCClaims) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromOIDC", ctx, claims)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFromOIDC indicates an expected call of CreateFromOIDC.
func (mr *MockSessionServiceMockRecorder) CreateFromOIDC(ctx, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromOIDC", reflect.TypeOf((*MockSessionService)(nil).CreateFromOIDC), ctx, claims)
}

// GetByID mocks base method.
func (m *MockSessionService) GetByID(ctx context.Context, id string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSessionServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSessionService)(nil).GetByID), ctx, id)
}
