// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/repository (interfaces: PersistentNameIDRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_persistent_nameid_repository.go -package=mocks . PersistentNameIDRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPersistentNameIDRepository is a mock of PersistentNameIDRepository interface.
type MockPersistentNameIDRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPersistentNameIDRepositoryMockRecorder
	isgomock struct{}
}

// MockPersistentNameIDRepositoryMockRecorder is the mock recorder for MockPersistentNameIDRepository.
type MockPersistentNameIDRepositoryMockRecorder struct {
	mock *MockPersistentNameIDRepository
}

// NewMockPersistentNameIDRepository creates a new mock instance.
func NewMockPersistentNameIDRepository(ctrl *gomock.Controller) *MockPersistentNameIDRepository {
	mock := &MockPersistentNameIDRepository{ctrl: ctrl}
	mock.recorder = &MockPersistentNameIDRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistentNameIDRepository) EXPECT() *MockPersistentNameIDRepositoryMockRecorder {
	return m.recorder
}

// GetOrCreate mocks base method.
func (m *MockPersistentNameIDRepository) GetOrCreate(ctx context.Context, entityID, userSubject string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", ctx, entityID, userSubject)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockPersistentNameIDRepositoryMockRecorder) GetOrCreate(ctx, entityID, userSubject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockPersistentNameIDRepository)(nil).GetOrCreate), ctx, entityID, userSubject)
}
