// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/identity-saml-provider/internal/service (interfaces: HydraClient)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_hydra_client.go -package=mocks . HydraClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/canonical/identity-saml-provider/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockHydraClient is a mock of HydraClient interface.
type MockHydraClient struct {
	ctrl     *gomock.Controller
	recorder *MockHydraClientMockRecorder
	isgomock struct{}
}

// MockHydraClientMockRecorder is the mock recorder for MockHydraClient.
type MockHydraClientMockRecorder struct {
	mock *MockHydraClient
}

// NewMockHydraClient creates a new mock instance.
func NewMockHydraClient(ctrl *gomock.Controller) *MockHydraClient {
	mock := &MockHydraClient{ctrl: ctrl}
	mock.recorder = &MockHydraClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHydraClient) EXPECT() *MockHydraClientMockRecorder {
	return m.recorder
}

// AuthCodeURL mocks base method.
func (m *MockHydraClient) AuthCodeURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthCodeURL indicates an expected call of AuthCodeURL.
func (mr *MockHydraClientMockRecorder) AuthCodeURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockHydraClient)(nil).AuthCodeURL), state)
}

// ExchangeCode mocks base method.
func (m *MockHydraClient) ExchangeCode(ctx context.Context, code string) (*domain.IDToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code)
	ret0, _ := ret[0].(*domain.IDToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockHydraClientMockRecorder) ExchangeCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockHydraClient)(nil).ExchangeCode), ctx, code)
}
