name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v**"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read
  packages: write

jobs:
  pre-commit:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/pre-commit.yaml

  build:
    uses: canonical/identity-team/.github/workflows/_rock-build.yaml@356ff61bd885e4147cc22c6eea64e4d806c889da # v1.11.3

  unit-test:
    uses: ./.github/workflows/unittest.yaml

  gh-publish:
    if: ${{ (github.ref == 'refs/heads/main') || (github.ref_type == 'tag') }}
    needs: [ build, unit-test ]
    uses: canonical/identity-team/.github/workflows/_rock-gh-publish.yaml@356ff61bd885e4147cc22c6eea64e4d806c889da # v1.11.3
    with:
      rock: ${{ needs.build.outputs.rock }}
