name: Update Copilot Instructions
on:
  schedule:
    - cron: '0 9 * * 1' # Run every Monday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-update:
    uses: canonical/copilot-collections/.github/workflows/auto_update_collections.yaml@9b23e98d7cb04d81e77cde1140a5700d8eb627bb # main
    secrets: inherit
