name: Update Copilot Instructions
on:
  schedule:
    - cron: '0 9 * * 1' # Run every Monday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-update:
    uses: canonical/copilot-collections/.github/workflows/auto_update_collections.yaml@c5644f61669b54e695554ac370aed3ae1a381e9b # main
    secrets: inherit
