name: Update Copilot Instructions
on:
  schedule:
    - cron: '0 9 * * 1' # Run every Monday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-update:
    uses: canonical/copilot-collections/.github/workflows/auto_update_collections.yaml@e75d6ec9dde0bd22893852f3ec4c8526a5b89321 # main
    secrets: inherit
